<?php

/**
 * Implements hook_entity_type_build(&$entity_types)
 */
function matts_module_entity_type_build(&$entity_types){
  if (isset($entity_types['node'])){
    $entity_types['node']->setClass('Drupal\matts_module\Plugins\Node\MattsNode');
  }
}
// Generates a random string. Useful when creating codes
function generate_string($input, $strength = 5) {
  $input_length = strlen($input);
  $random_string = '';
  for($i = 0; $i < $strength; $i++) {
      $random_character = $input[mt_rand(0, $input_length - 1)];
      $random_string .= $random_character;
  }

  return $random_string;
}
function matts_module_theme(){
  return [
    'ticket' => [
      'template' => 'ticket',
      'variables' => [
          'title' => NULL,
          'code' => '',
          'first_name' => '',
          'last_name' => '',
          'full_name' => '',
          'greeting_name' => '',
          'show_apple_wallet'=>true
      ]
    ]
  ];
}
